name: access-granudrum-calibration-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - opencv
  - plotly
  - python-kaleido
  - matplotlib
  - pip
  - pip:
    - nbgitpuller
    - konigcell>=0.2
    - coexist>=0.3


